security:
    providers:
        maindb:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: maindb
            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard
            logout:
                path:   /logout
                target: /

    access_control:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        App\Entity\User:
            algorithm: bcrypt